version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: aerosense
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    env_file:
      - .env.example
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    restart: always
    env_file:
      - .env.example
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:
